spring:
  datasource:
    url: jdbc:postgresql://product_db:5432/productdb
    username: productservice
    password: product
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  server:
    port: 8085
  application:
    name: productservice
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /