package com.huongque.notiservice.enums;

public enum NotificationEventType {
    USER_REGISTERED,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,
    PASSWORD_CHANGED,
    ORDER_PLACED,
    ORDER_CONFIRMED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    REFUND_ISSUED,
    DISCOUNT_AVAILABLE,
    CART_ABANDONED,
    ITEM_BACK_IN_STOCK,
    PRICE_DROP,
    ACCOUNT_BANNED,
    ACCOUNT_VERIFIED,
    SUPPORT_RESPONSE
}
