server:
  port: 8080

spring:
  application:
    name: apigateway

  cloud:
    gateway:
      routes:
        - id: websocket-nofi
          uri: ws://notiservice:8092
          predicates:
            - Path=/ws/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        corsConfigurations:
          '[/**]':  # Áp dụng cho tất cả các route
            allowedOrigins:
              - "http://localhost:3000"  # Cho phép origin của frontend
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"  # Cho phép mọi header, bao gồm Authorization, X-Tenant-ID, Content-Type...
            allowCredentials: true  # Nếu frontend gửi cookie hoặc token

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/
    registry-fetch-interval-seconds: 30
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 8
    eureka-server-total-connections: 200
    eureka-server-total-connections-per-host: 50
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

jwt:
  signing-key: ${JWT_SIGNING_KEY}
