version: '3.8'

services:
  orderservice:
    build: .
    ports:
      - "8888:8888"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/orderservice?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql
    networks:
      - orderservice-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=orderservice
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - orderservice-network

networks:
  orderservice-network:
    driver: bridge

volumes:
  mysql-data: 