# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /

# Copy the built JAR file into the container
COPY target/adminservice-0.0.1-SNAPSHOT.jar app.jar

# Expose the application port (change it based on your service configuration)
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "app.jar"]