# Stage 1: Build the application
FROM openjdk:21-jdk-slim AS build
WORKDIR /

# Copy Maven configuration files
COPY pom.xml ./
COPY mvnw ./
COPY .mvn ./.mvn

# Copy the source code
COPY src ./src

# Copy the .env file
COPY .env ./

# Build the application (skip tests for speed, optional)
RUN ./mvnw clean package -DskipTests

# Stage 2: Create the runtime image
FROM openjdk:21-jdk-slim
WORKDIR /

# Copy the built JAR from the build stage
COPY --from=build /target/adminservice-0.0.1-SNAPSHOT.jar app.jar



# Run the JAR file
ENTRYPOINT ["java", "-jar", "app.jar"]