services:
  adminservice:
    build:
      context: ./adminservice
      dockerfile: dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
    env_file:
      - ./adminservice/.env

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: always

networks:
  default:
    driver: bridge