services:
  # adminservice:
  #   build:
  #     context: ./adminservice
  #     dockerfile: dockerfile
  #   ports:
  #     - "8081:8080"
  #   depends_on:
  #     - rabbitmq
  #   env_file:
  #     - ./adminservice/.env
  authservice:
    build:
      context: ./authservice
      dockerfile: dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - rabbitmq
    env_file:
      - ./authservice/.env
  userservice:
    build:
      context: ./userservice
      dockerfile: dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - rabbitmq
    env_file:
      - ./userservice/.env

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: always

networks:
  default:
    driver: bridge